# Creacion de un indice de confianza de paga de para cada registro

In [2]:
import pandas as pd
import numpy as np
from GettinTheData import df_bd_grados_georref

In [4]:
df_bd_grados_georref

      Latitud  Longitud  Ubicaciones  ... 61-90 91-120      121+
0      3.4516  -76.5320         Cali  ...   0.0    0.0      0.00
1      4.4447  -75.2424       Ibagué  ...   0.0    0.0      0.00
2     10.4631  -73.2532   Valledupar  ...   0.0    0.0      0.00
3      7.8891  -72.4967       Cúcuta  ...   0.0    0.0      0.00
4      7.8891  -72.4967       Cúcuta  ...   0.0    0.0      0.00
...       ...       ...          ...  ...   ...    ...       ...
6688   7.1193  -73.1227  Bucaramanga  ...   0.0    0.0  47130.50
6689   5.0689  -75.5174    Manizales  ...   0.0    0.0      0.00
6690   6.2442  -75.5812     Medellín  ...   0.0    0.0      0.00
6691  10.3910  -75.4794    Cartagena  ...   0.0    0.0      0.00
6692  10.3910  -75.4794    Cartagena  ...   0.0    0.0  16058.69

[6693 rows x 14 columns]